#!/usr/bin/env python
"""
Auto-Generated by Hermes AI
Session: Session_DIXON_1776700748
"""
from openalgo import api
import pandas as pd
import numpy as np
import time
import os

api_key = os.getenv('OPENALGO_API_KEY')
host    = os.getenv('HOST_SERVER', 'http://127.0.0.1:5000')

if not api_key:
    print("Error: OPENALGO_API_KEY environment variable not set")
    exit(1)

client = api(api_key=api_key, host=host)

def evaluate(df, params):
    # Moving Average Crossover
    fast_window = params.get('fast_window', 10)
    slow_window = params.get('slow_window', 30)
    fast_ma = vbt.MA.run(df['close'], window=fast_window).ma
    slow_ma = vbt.MA.run(df['close'], window=slow_window).ma

    # RSI for confirmation
    rsi_window = params.get('rsi_window', 14)
    rsi = vbt.RSI.run(df['close'], window=rsi_window).rsi

    # Bollinger Bands for volatility
    bb_window = params.get('bb_window', 20)
    bb_alpha = params.get('bb_alpha', 2)
    bb = vbt.BBANDS.run(df['close'], window=bb_window, alpha=bb_alpha)
    upper_bb = bb.upper
    lower_bb = bb.lower

    # Entry conditions: Fast MA crosses above Slow MA, RSI below 70, price above lower BB
    entries = (
        (fast_ma > slow_ma) &
        (rsi < params.get('rsi_upper', 70)) &
        (df['close'] > lower_bb)
    )

    # Exit conditions: Fast MA crosses below Slow MA, RSI above 30, price below upper BB
    exits = (
        (fast_ma < slow_ma) &
        (rsi > params.get('rsi_lower', 30)) &
        (df['close'] < upper_bb)
    )

    # No short positions
    short_entries = None
    short_exits = None

    return entries, exits, short_entries, short_exits

PARAM_RANGES = {
    "fast_window": range(5, 20, 1),
    "slow_window": range(20, 50, 2),
    "rsi_window": range(10, 20, 1),
    "rsi_lower": range(20, 40, 2),
    "rsi_upper": range(60, 80, 2),
    "bb_window": range(10, 30, 2),
    "bb_alpha": [1.0, 1.5, 2.0, 2.5, 3.0]
}

def main():
    print("Starting AI Strategy...")
    # Add live loop execution logic here utilizing the `evaluate` function.
    
if __name__ == "__main__":
    main()
