#!/usr/bin/env python
"""
Auto-Generated by Hermes AI
Session: Session_SBIN_1776704978
"""
from openalgo import api
import pandas as pd
import numpy as np
import time
import os

api_key = os.getenv('OPENALGO_API_KEY')
host    = os.getenv('HOST_SERVER', 'http://127.0.0.1:5000')

if not api_key:
    print("Error: OPENALGO_API_KEY environment variable not set")
    exit(1)

client = api(api_key=api_key, host=host)

def evaluate(df, params):
    # Strategy: Momentum breakout with ATR-based stop and volume confirmation
    rsi = run_indicator('RSI', df['close'], window=params.get('rsi_window', 14))
    atr = get_atr(df['high'], df['low'], df['close'], window=params.get('atr_window', 14))
    volume_ma = df['volume'].rolling(window=params.get('volume_ma_window', 20)).mean()
    
    # Entry: RSI breaking above oversold + volume surge + price above short MA
    entries = (rsi > params.get('rsi_entry_level', 30)) & \
              (rsi.shift(1) <= params.get('rsi_entry_level', 30)) & \
              (df['volume'] > volume_ma * params.get('volume_multiplier', 1.8)) & \
              (df['close'] > df['close'].rolling(window=params.get('price_ma_window', 10)).mean())
    
    # Exit: RSI overbought OR price reversal below ATR stop
    exits = (rsi > params.get('rsi_exit_level', 70)) | \
            (df['close'] < df['close'].shift(1) - atr * params.get('atr_multiplier', 1.5))
    
    return entries, exits, None, None

PARAM_RANGES = {
    "rsi_window": range(10, 20, 2),
    "atr_window": range(10, 20, 2),
    "volume_ma_window": range(15, 30, 3),
    "price_ma_window": range(8, 15, 2),
    "rsi_entry_level": range(25, 40, 3),
    "rsi_exit_level": range(65, 85, 3),
    "volume_multiplier": [1.5, 1.8, 2.0],
    "atr_multiplier": [1.3, 1.5, 1.8]
}

def main():
    print("Starting AI Strategy...")
    # Add live loop execution logic here utilizing the `evaluate` function.
    
if __name__ == "__main__":
    main()
